default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e7
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    summary_freq: 5000
    use_recurrent: false
    vis_encode_type: simple
    sequence_length: 64
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

GladiatorAgentBurstV3:
    batch_size: 2048
    buffer_size: 20480
    hidden_units: 512
    time_horizon: 1000
    self_play:
        window: 10
        play_against_latest_model_ratio: 0.5
        save_steps: 50000
        swap_steps: 50000
        team_change: 200000

RTSAgent:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 256
    beta: 5.0e-3
    buffer_size: 256
    max_steps: 500000
    summary_freq: 20000
    time_horizon: 5
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.9
